[package]
name = "solana-rpc"
version = "1.11.7"
description = "Solana RPC"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-rpc"
edition = "2021"

[dependencies]
base64 = "0.13.0"
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
dashmap = "5.4.0"
#das_api = { git = "https://github.com/GenesysGo/digital-asset-rpc-infrastructure.git", branch = "cavey/das_api_version" }
#digital_asset_types = { git = "https://github.com/GenesysGo/digital-asset-rpc-infrastructure.git", branch = "cavey/das_api_version" }
das_api = { path = "../../digital-asset-rpc-infrastructure/das_api" }
digital_asset_types = { path = "../../digital-asset-rpc-infrastructure/digital_asset_types" }
itertools = "0.10.3"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0" }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
libc = "0.2.126"
log = "0.4.17"
rayon = "1.5.3"
regex = "1.5.6"
serde = "1.0.138"
serde_derive = "1.0.103"
serde_json = "1.0.81"
soketto = "0.7"
solana-account-decoder = { path = "../account-decoder", version = "=1.11.7" }
solana-client = { path = "../client", version = "=1.11.7" }
solana-entry = { path = "../entry", version = "=1.11.7" }
solana-faucet = { path = "../faucet", version = "=1.11.7" }
solana-gossip = { path = "../gossip", version = "=1.11.7" }
solana-ledger = { path = "../ledger", version = "=1.11.7" }
solana-measure = { path = "../measure", version = "=1.11.7" }
solana-metrics = { path = "../metrics", version = "=1.11.7" }
solana-perf = { path = "../perf", version = "=1.11.7" }
solana-poh = { path = "../poh", version = "=1.11.7" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.11.7" }
solana-runtime = { path = "../runtime", version = "=1.11.7" }
solana-sdk = { path = "../sdk", version = "=1.11.7" }
solana-send-transaction-service = { path = "../send-transaction-service", version = "=1.11.7" }
solana-stake-program = { path = "../programs/stake", version = "=1.11.7" }
solana-storage-bigtable = { path = "../storage-bigtable", version = "=1.11.7" }
solana-streamer = { path = "../streamer", version = "=1.11.7" }
solana-transaction-status = { path = "../transaction-status", version = "=1.11.7" }
solana-version = { path = "../version", version = "=1.11.7" }
solana-vote-program = { path = "../programs/vote", version = "=1.11.7" }
spl-token = { git = "https://github.com/solana-labs/solana-program-library/", features = ["no-entrypoint"] }
spl-token-2022 = { git = "https://github.com/solana-labs/solana-program-library/", features = ["no-entrypoint"] }
stream-cancel = "0.8.1"
thiserror = "1.0"
tokio = { version = "~1.16", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec", "compat"] }

[dev-dependencies]
env_logger = "0.9.0"
log = "0.4.17"
serial_test = "0.9.0"
solana-address-lookup-table-program = { path = "../programs/address-lookup-table", version = "=1.11.7" }
solana-net-utils = { path = "../net-utils", version = "=1.11.7" }
solana-stake-program = { path = "../programs/stake", version = "=1.11.7" }
symlink = "0.1.0"

[lib]
crate-type = ["lib"]
name = "solana_rpc"

[features]
default = []
metaplex = []

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
